import React, { useState } from 'react';
import JSZip from 'jszip';
import { MoleculeStructure, SimulationProtocol, LammpsProtocol } from '../types/gromacs';
import { generateDockerCommand, generateIonsMdp, generateMinimMdp, generateNptMdp, generateNvtMdp, generateProductionMdp, generateRunBashScript, generateSlurmScript } from '../utils/mdpGenerator';
import { generateLammpsInput, generateLammpsBashScript, generateLammpsSlurmScript } from '../utils/lammpsGenerator';
import { Check, Copy, Download, FileArchive, Terminal, X } from 'lucide-react';

interface ScriptExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  structure: MoleculeStructure | null;
  protocol: SimulationProtocol;
  lammpsProtocol: LammpsProtocol;
}

export const ScriptExportModal: React.FC<ScriptExportModalProps> = ({
  isOpen,
  onClose,
  structure,
  protocol,
  lammpsProtocol,
}) => {
  const [activeTab, setActiveTab] = useState<'gmx_bash' | 'gmx_slurm' | 'lmp_in' | 'lmp_bash' | 'lmp_slurm'>('gmx_bash');
  const [exportPackageType, setExportPackageType] = useState<'gromacs' | 'lammps' | 'both'>('both');
  const [isZipping, setIsZipping] = useState(false);
  const [copiedTab, setCopiedTab] = useState<string | null>(null);

  if (!isOpen) return null;

  const gmxBash = generateRunBashScript(protocol, structure?.filename || 'input.pdb');
  const gmxSlurm = generateSlurmScript(protocol);
  const lmpIn = generateLammpsInput(lammpsProtocol);
  const lmpBash = generateLammpsBashScript(lammpsProtocol);
  const lmpSlurm = generateLammpsSlurmScript(lammpsProtocol);

  const getCurrentCode = () => {
    switch (activeTab) {
      case 'gmx_bash':
        return gmxBash;
      case 'gmx_slurm':
        return gmxSlurm;
      case 'lmp_in':
        return lmpIn;
      case 'lmp_bash':
        return lmpBash;
      case 'lmp_slurm':
        return lmpSlurm;
      default:
        return gmxBash;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCurrentCode());
    setCopiedTab(activeTab);
    setTimeout(() => setCopiedTab(null), 2000);
  };

  const handleDownloadZip = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();
      const sysClean = protocol.systemName.replace(/[^a-zA-Z0-9]/g, '_');

      // 1. GROMACS files
      if (exportPackageType === 'gromacs' || exportPackageType === 'both') {
        const gmxFolder = exportPackageType === 'both' ? zip.folder('01_gromacs') : zip.folder(`gmx_${sysClean}`);
        if (gmxFolder) {
          gmxFolder.file('ions.mdp', generateIonsMdp());
          gmxFolder.file('minim.mdp', generateMinimMdp(protocol));
          gmxFolder.file('nvt.mdp', generateNvtMdp(protocol));
          gmxFolder.file('npt.mdp', generateNptMdp(protocol));
          gmxFolder.file('md.mdp', generateProductionMdp(protocol));
          gmxFolder.file('run_pipeline.sh', gmxBash);
          gmxFolder.file('submit_slurm.sh', gmxSlurm);
          gmxFolder.file('README_GROMACS.md', `# GROMACS Run Guide\nExecute: \`bash run_pipeline.sh\` or \`sbatch submit_slurm.sh\``);
        }
      }

      // 2. LAMMPS files
      if (exportPackageType === 'lammps' || exportPackageType === 'both') {
        const lmpFolder = exportPackageType === 'both' ? zip.folder('02_lammps') : zip.folder(`lmp_${sysClean}`);
        if (lmpFolder) {
          lmpFolder.file('in.lammps', lmpIn);
          lmpFolder.file('run_lammps.sh', lmpBash);
          lmpFolder.file('submit_lammps_slurm.sh', lmpSlurm);
          lmpFolder.file('README_LAMMPS.md', `# LAMMPS Run Guide\nExecute: \`bash run_lammps.sh\` or \`sbatch submit_lammps_slurm.sh\``);
        }
      }

      // Root comparative README
      const masterReadme = `# Molecular Dynamics Simulation Bundle: GROMACS vs. LAMMPS
System: ${protocol.systemName}
Generated by GMX & LAMMPS Comparative MD Studio

## Structure
- /01_gromacs: Full GROMACS pipeline (pdb2gmx, editconf, solvate, genion, minim, nvt, npt, md)
- /02_lammps: LAMMPS molecular dynamics script (in.lammps, run_lammps.sh, submit_lammps_slurm.sh)

## Comparative Notes
- GROMACS uses ${protocol.forceField} with ${protocol.waterModel} water model (${protocol.temperature} K, ${protocol.pressure} bar)
- LAMMPS uses ${lammpsProtocol.units} units with ${lammpsProtocol.pairStyle} and ${lammpsProtocol.kspaceStyle}
`;
      zip.file('README_COMPARATIVE.md', masterReadme);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `md_${sysClean}_${exportPackageType}_package.zip`;
      a.click();
    } catch (err) {
      console.error('Failed generating zip', err);
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm">
      <div className="w-full max-w-4xl rounded-xl border border-slate-800 bg-[#0B0F19] shadow-2xl flex flex-col max-h-[85vh] overflow-hidden">
        {/* Modal Header */}
        <div className="px-5 py-3.5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileArchive className="w-5 h-5 text-cyan-400" />
            <h3 className="text-sm font-semibold text-slate-100 font-mono">
              Export Simulation Package (GROMACS & LAMMPS)
            </h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-200 p-1 rounded-lg"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Script Selection Tabs */}
        <div className="px-5 py-2.5 border-b border-slate-800 bg-slate-900/60 flex flex-wrap items-center justify-between gap-2">
          <div className="flex flex-wrap items-center gap-1 p-1 bg-slate-950 rounded-lg border border-slate-800">
            {/* GROMACS Scripts */}
            <button
              onClick={() => setActiveTab('gmx_bash')}
              className={`px-2.5 py-1 text-xs font-mono rounded transition-colors ${
                activeTab === 'gmx_bash' ? 'bg-cyan-500/20 text-cyan-300' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              GMX run_pipeline.sh
            </button>
            <button
              onClick={() => setActiveTab('gmx_slurm')}
              className={`px-2.5 py-1 text-xs font-mono rounded transition-colors ${
                activeTab === 'gmx_slurm' ? 'bg-cyan-500/20 text-cyan-300' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              GMX slurm.sh
            </button>

            <span className="w-px h-3.5 bg-slate-800 mx-1" />

            {/* LAMMPS Scripts */}
            <button
              onClick={() => setActiveTab('lmp_in')}
              className={`px-2.5 py-1 text-xs font-mono rounded transition-colors ${
                activeTab === 'lmp_in' ? 'bg-amber-500/20 text-amber-300' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              LMP in.lammps
            </button>
            <button
              onClick={() => setActiveTab('lmp_bash')}
              className={`px-2.5 py-1 text-xs font-mono rounded transition-colors ${
                activeTab === 'lmp_bash' ? 'bg-amber-500/20 text-amber-300' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              LMP run_lammps.sh
            </button>
            <button
              onClick={() => setActiveTab('lmp_slurm')}
              className={`px-2.5 py-1 text-xs font-mono rounded transition-colors ${
                activeTab === 'lmp_slurm' ? 'bg-amber-500/20 text-amber-300' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              LMP slurm.sh
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="text-xs font-mono text-slate-300 hover:text-white px-3 py-1 rounded bg-slate-800 border border-slate-700 flex items-center gap-1.5 transition-colors"
          >
            {copiedTab === activeTab ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy Script</span>
              </>
            )}
          </button>
        </div>

        {/* Code Content Viewport */}
        <div className="flex-1 p-5 overflow-y-auto bg-[#07090E] font-mono text-xs text-slate-300 leading-relaxed">
          <pre className="whitespace-pre">{getCurrentCode()}</pre>
        </div>

        {/* Modal Footer with Archive Options */}
        <div className="px-5 py-3.5 border-t border-slate-800 bg-slate-900/80 flex flex-wrap items-center justify-between gap-3">
          {/* Bundle selector */}
          <div className="flex items-center gap-2 text-xs font-mono">
            <span className="text-slate-400">Bundle Contents:</span>
            <div className="flex p-0.5 bg-slate-950 border border-slate-800 rounded">
              <button
                onClick={() => setExportPackageType('both')}
                className={`px-2 py-0.5 rounded transition-colors ${exportPackageType === 'both' ? 'bg-slate-800 text-white font-semibold' : 'text-slate-400'}`}
              >
                Both (Comparative)
              </button>
              <button
                onClick={() => setExportPackageType('gromacs')}
                className={`px-2 py-0.5 rounded transition-colors ${exportPackageType === 'gromacs' ? 'bg-cyan-950 text-cyan-300' : 'text-slate-400'}`}
              >
                GROMACS Only
              </button>
              <button
                onClick={() => setExportPackageType('lammps')}
                className={`px-2 py-0.5 rounded transition-colors ${exportPackageType === 'lammps' ? 'bg-amber-950 text-amber-300' : 'text-slate-400'}`}
              >
                LAMMPS Only
              </button>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={onClose}
              className="px-3.5 py-1.5 text-xs font-mono text-slate-300 hover:text-white transition-colors"
            >
              Close
            </button>

            <button
              onClick={handleDownloadZip}
              disabled={isZipping}
              className="px-4 py-2 text-xs font-medium text-slate-950 bg-cyan-400 hover:bg-cyan-300 disabled:opacity-50 rounded-lg transition-colors font-mono font-semibold flex items-center gap-2 shadow-sm"
            >
              <Download className="w-4 h-4" />
              <span>{isZipping ? 'Archiving...' : 'Download Simulation Package (.ZIP)'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
