import { Atom, MoleculeStructure, Residue, XvgSeries, LammpsProtocol, SimulationProtocol } from '../types/gromacs';

export function generateLammpsInput(protocol: LammpsProtocol, dataFile = 'data.lammps'): string {
  const isReal = protocol.units === 'real';
  const isMetal = protocol.units === 'metal';

  return `# ==============================================================================
# LAMMPS Molecular Dynamics Input Script
# System: ${protocol.systemName}
# Units: ${protocol.units} | Atom Style: ${protocol.atomStyle} | Ensemble: ${protocol.ensemble.toUpperCase()}
# Generated by GMX & LAMMPS Comparative MD Studio
# ==============================================================================

# 1. Initialization
units           ${protocol.units}
atom_style      ${protocol.atomStyle}
boundary        ${protocol.boundary}

# 2. Potential Definition
pair_style      ${protocol.pairStyle}
${protocol.kspaceStyle ? `kspace_style    ${protocol.kspaceStyle}` : ''}

# 3. Read System Data
read_data       ${dataFile}

# Pair coefficients
${protocol.pairCoeff}

# Neighbor list settings
neighbor        ${isReal ? '2.0' : (isMetal ? '2.0' : '0.3')} bin
neigh_modify    delay 0 every 1 check yes

# 4. Energy Minimization
${protocol.minimization ? `# Steepest descent & conjugate gradient minimization
thermo          50
thermo_style    custom step temp pe ke etotal press
min_style       cg
minimize        1.0e-4 1.0e-6 1000 10000
reset_timestep  0
` : '# Minimization bypassed'}

# 5. Velocity Initialization & Ensembles
velocity        all create ${protocol.temperature} 12345 dist gaussian mom yes rot yes
timestep        ${protocol.timeStep}

# Setup Integrator & Thermostat/Barostat
${protocol.ensemble === 'nvt' ? `# NVT Ensemble (Nosé-Hoover Thermostat)
fix             1 all nvt temp ${protocol.temperature} ${protocol.temperature} ${isReal ? '100.0' : (isMetal ? '0.1' : '1.0')}
` : (protocol.ensemble === 'npt' ? `# NPT Ensemble (Nosé-Hoover Thermostat + Barostat)
fix             1 all npt temp ${protocol.temperature} ${protocol.temperature} ${isReal ? '100.0' : (isMetal ? '0.1' : '1.0')} iso ${protocol.pressure} ${protocol.pressure} ${isReal ? '1000.0' : (isMetal ? '1.0' : '10.0')}
` : `# NVE Microcanonical Ensemble
fix             1 all nve
`)}

# 6. Outputs & Trajectory Trajectories
thermo          ${protocol.thermoFreq}
thermo_style    custom step time temp pe ke etotal press vol density
dump            1 all custom ${protocol.dumpFreq} trajectory.lammpstrj id type x y z vx vy vz
dump_modify     1 sort id

# 7. Production Run
run             ${protocol.runSteps}

# Clean termination
unfix           1
undump          1
`;
}

// Convert GROMACS SimulationProtocol to equivalent LAMMPS LammpsProtocol
export function convertGromacsToLammpsProtocol(gmx: SimulationProtocol): LammpsProtocol {
  return {
    systemName: `${gmx.systemName} (LAMMPS)`,
    units: 'real', // real units for biomolecules (Å, fs, kcal/mol, atm)
    atomStyle: 'full', // full for charge + molecular topology
    boundary: 'p p p', // periodic in xyz
    pairStyle: 'lj/cut/coul/long 10.0 10.0', // 10 Å = 1.0 nm cutoff
    pairCoeff: 'pair_coeff      * * 0.100 3.200 # Standard VDW coefficients',
    kspaceStyle: 'pppm 1.0e-4', // Particle-Particle Particle-Mesh (equivalent to PME)
    temperature: gmx.temperature,
    pressure: gmx.pressure * 0.986923, // convert bar to atm
    timeStep: gmx.timeStepFs, // in fs for real units
    runSteps: Math.round((gmx.prodLengthNs * 1000 * 1000) / gmx.timeStepFs),
    thermoFreq: 1000,
    dumpFreq: 5000,
    ensemble: 'npt',
    minimization: true,
    gpuAcceleration: gmx.gpuAcceleration,
  };
}

export function parseLammpsData(content: string, filename = 'data.lammps'): MoleculeStructure {
  const lines = content.split('\n');
  let numAtoms = 0;
  let numAtomTypes = 0;
  let xlo = 0, xhi = 50;
  let ylo = 0, yhi = 50;
  let zlo = 0, zhi = 50;

  let inAtomsSection = false;
  const atoms: Atom[] = [];
  const residueMap = new Map<string, Residue>();

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line || line.startsWith('#')) continue;

    // Header declarations
    if (line.includes('atoms')) {
      numAtoms = parseInt(line.split(/\s+/)[0], 10) || 0;
    } else if (line.includes('atom types')) {
      numAtomTypes = parseInt(line.split(/\s+/)[0], 10) || 1;
    } else if (line.includes('xlo xhi')) {
      const parts = line.split(/\s+/);
      xlo = parseFloat(parts[0]) || 0;
      xhi = parseFloat(parts[1]) || 50;
    } else if (line.includes('ylo yhi')) {
      const parts = line.split(/\s+/);
      ylo = parseFloat(parts[0]) || 0;
      yhi = parseFloat(parts[1]) || 50;
    } else if (line.includes('zlo zhi')) {
      const parts = line.split(/\s+/);
      zlo = parseFloat(parts[0]) || 0;
      zhi = parseFloat(parts[1]) || 50;
    } else if (line.startsWith('Atoms')) {
      inAtomsSection = true;
      continue;
    } else if (inAtomsSection) {
      if (line.match(/^[A-Za-z]/)) {
        // Reached another section (Velocities, Bonds, etc.)
        inAtomsSection = false;
        continue;
      }

      // Parse atom line
      // Standard "full" style: id molecule-tag atom-type q x y z
      // Standard "atomic" style: id atom-type x y z
      const parts = line.split(/\s+/);
      if (parts.length >= 5) {
        const id = parseInt(parts[0], 10);
        let atomType = 1;
        let q = 0;
        let x = 0, y = 0, z = 0;
        let molId = 1;

        if (parts.length >= 7) {
          // full style: id mol type q x y z
          molId = parseInt(parts[1], 10) || 1;
          atomType = parseInt(parts[2], 10) || 1;
          q = parseFloat(parts[3]) || 0;
          x = parseFloat(parts[4]);
          y = parseFloat(parts[5]);
          z = parseFloat(parts[6]);
        } else {
          // atomic style: id type x y z
          atomType = parseInt(parts[1], 10) || 1;
          x = parseFloat(parts[2]);
          y = parseFloat(parts[3]);
          z = parseFloat(parts[4]);
        }

        if (isNaN(x) || isNaN(y) || isNaN(z)) continue;

        // Map atom types to pseudo-elements for visualization
        const elementMapping = ['C', 'H', 'O', 'N', 'S', 'P', 'CL', 'NA', 'FE', 'CU'];
        const element = elementMapping[(atomType - 1) % elementMapping.length] || 'C';

        const resSeq = molId;
        const resName = `MOL${molId}`;

        const atom: Atom = {
          id,
          name: `${element}${id}`,
          resName,
          resSeq,
          chainID: 'A',
          x,
          y,
          z,
          element,
          charge: q,
          isBackbone: atomType === 1,
        };

        atoms.push(atom);

        const resKey = `A_${resSeq}_${resName}`;
        if (!residueMap.has(resKey)) {
          residueMap.set(resKey, {
            seq: resSeq,
            name: resName,
            chain: 'A',
            atoms: [],
          });
        }
        residueMap.get(resKey)!.atoms.push(atom);
      }
    }
  }

  const boxX = Math.abs(xhi - xlo);
  const boxY = Math.abs(yhi - ylo);
  const boxZ = Math.abs(zhi - zlo);

  return {
    name: filename.replace(/\.[^/.]+$/, ''),
    filename,
    atoms,
    residues: Array.from(residueMap.values()),
    chains: ['A'],
    box: {
      x: boxX || 40,
      y: boxY || 40,
      z: boxZ || 40,
      type: 'cubic',
    },
    totalCharge: 0,
    numAtoms: atoms.length,
    numResidues: residueMap.size,
    massApprox: Math.round((atoms.length * 12.0) / 100) / 10,
  };
}

export function parseLammpsLog(content: string): {
  series: Record<string, XvgSeries>;
  warnings: string[];
} {
  const lines = content.split('\n');
  const warnings: string[] = [];
  const seriesMap: Record<string, { x: number; y: number }[]> = {
    temp: [],
    pe: [],
    ke: [],
    etotal: [],
    press: [],
  };

  let inThermo = false;
  let colIndices: Record<string, number> = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.includes('WARNING') || trimmed.includes('ERROR')) {
      warnings.push(trimmed);
    }

    if (trimmed.startsWith('Step') && (trimmed.includes('Temp') || trimmed.includes('TotEng') || trimmed.includes('Press'))) {
      inThermo = true;
      const headers = trimmed.split(/\s+/);
      colIndices = {};
      headers.forEach((h, idx) => {
        colIndices[h.toLowerCase()] = idx;
      });
      continue;
    }

    if (inThermo) {
      if (trimmed.startsWith('Loop time') || trimmed.startsWith('Performance:') || !trimmed) {
        inThermo = false;
        continue;
      }

      const parts = trimmed.split(/\s+/);
      const stepIdx = colIndices['step'] ?? 0;
      const step = parseFloat(parts[stepIdx]);
      if (isNaN(step)) continue;

      if (colIndices['temp'] !== undefined && parts[colIndices['temp']]) {
        const val = parseFloat(parts[colIndices['temp']]);
        if (!isNaN(val)) seriesMap.temp.push({ x: step, y: val });
      }
      if (colIndices['pe'] !== undefined && parts[colIndices['pe']]) {
        const val = parseFloat(parts[colIndices['pe']]);
        if (!isNaN(val)) seriesMap.pe.push({ x: step, y: val });
      }
      if (colIndices['ke'] !== undefined && parts[colIndices['ke']]) {
        const val = parseFloat(parts[colIndices['ke']]);
        if (!isNaN(val)) seriesMap.ke.push({ x: step, y: val });
      }
      if (colIndices['etotal'] !== undefined && parts[colIndices['etotal']]) {
        const val = parseFloat(parts[colIndices['etotal']]);
        if (!isNaN(val)) seriesMap.etotal.push({ x: step, y: val });
      }
      if (colIndices['press'] !== undefined && parts[colIndices['press']]) {
        const val = parseFloat(parts[colIndices['press']]);
        if (!isNaN(val)) seriesMap.press.push({ x: step, y: val });
      }
    }
  }

  const result: Record<string, XvgSeries> = {};
  for (const [key, data] of Object.entries(seriesMap)) {
    if (data.length > 0) {
      result[key] = {
        id: `lammps_${key}`,
        title: `LAMMPS ${key.toUpperCase()} Evolution`,
        xLabel: 'Timestep',
        yLabel: key.toUpperCase(),
        unitX: 'steps',
        unitY: key === 'temp' ? 'K' : (key === 'press' ? 'bars/atm' : 'energy'),
        data,
      };
    }
  }

  return { series: result, warnings };
}

export function generateLammpsBashScript(protocol: LammpsProtocol): string {
  const gpuFlag = protocol.gpuAcceleration ? '-sf gpu -pk gpu 1' : '';

  return `#!/usr/bin/env bash
# ==============================================================================
# LAMMPS High-Performance Execution Script
# System: ${protocol.systemName}
# ==============================================================================
set -euo pipefail

echo "==> Running LAMMPS Molecular Dynamics Simulation..."
# Run using standard MPI executable with 8 threads
mpirun -np 8 lmp -in in.lammps ${gpuFlag} -log log.lammps

echo "==> Extracting Thermodynamic Properties from log.lammps..."
# Grep thermodynamic table for post-processing
awk '/Step Temp/,/Loop time/' log.lammps > thermo_extracted.txt

echo "==> LAMMPS Simulation Completed Successfully!"
`;
}

export function generateLammpsSlurmScript(protocol: LammpsProtocol): string {
  return `#!/bin/bash
#SBATCH --job-name=lmp_${protocol.systemName.replace(/[^a-zA-Z0-9]/g, '_')}
#SBATCH --output=lmp_%j.log
#SBATCH --error=lmp_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --time=24:00:00
#SBATCH --partition=gpu

module purge
module load lammps/2023-cuda-openmpi

export OMP_NUM_THREADS=1

echo "Starting LAMMPS on \$(hostname) with \${SLURM_NTASKS} MPI ranks"
bash run_lammps.sh
echo "Finished at \$(date)"
`;
}
